[package]
name = "istherepie-hello_world"
version = "0.0.1"
authors = ["Steffen Park <dev@istherepie.com>"]
edition = "2018"

description = "Testing how crates.io works"
repository = "https://github.com/istherepie/hello_rust"
readme = "README.md"

license = "MIT"
license-file = "LICENSE"

